// <auto-generated />
using System;
using HistoryConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HistoryConnect.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HistoryConnect.Models.Administrator", b =>
                {
                    b.Property<int>("IdUtilizator")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilizator");

                    b.Property<DateTime>("DataNumire")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_numire");

                    b.HasKey("IdUtilizator");

                    b.ToTable("administrator", (string)null);
                });

            modelBuilder.Entity("HistoryConnect.Models.Avatar", b =>
                {
                    b.Property<int>("IdAvatar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_avatar");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAvatar"));

                    b.Property<int>("NivelNecesar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("nivel_necesar");

                    b.Property<string>("NumeAvatar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nume_avatar");

                    b.Property<string>("UrlPoza")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("url_poza");

                    b.HasKey("IdAvatar");

                    b.HasIndex("NumeAvatar")
                        .IsUnique();

                    b.ToTable("avatar", null, t =>
                        {
                            t.HasCheckConstraint("CK_avatar_nivel_necesar_valid", "nivel_necesar >= 1 AND nivel_necesar <= 20");
                        });

                    b.HasData(
                        new
                        {
                            IdAvatar = 1,
                            NivelNecesar = 1,
                            NumeAvatar = "Default",
                            UrlPoza = "Poze/avatar_default.png"
                        },
                        new
                        {
                            IdAvatar = 2,
                            NivelNecesar = 3,
                            NumeAvatar = "Burebista",
                            UrlPoza = "Poze/Burebista.png"
                        },
                        new
                        {
                            IdAvatar = 3,
                            NivelNecesar = 5,
                            NumeAvatar = "Decebal",
                            UrlPoza = "Poze/Decebal.png"
                        },
                        new
                        {
                            IdAvatar = 4,
                            NivelNecesar = 7,
                            NumeAvatar = "Traian",
                            UrlPoza = "Poze/Traian.png"
                        },
                        new
                        {
                            IdAvatar = 5,
                            NivelNecesar = 10,
                            NumeAvatar = "Vlad Tepes",
                            UrlPoza = "Poze/Vlad_Tepes.png"
                        },
                        new
                        {
                            IdAvatar = 6,
                            NivelNecesar = 13,
                            NumeAvatar = "Stefan cel Mare",
                            UrlPoza = "Poze/Stefan_cel_Mare.png"
                        },
                        new
                        {
                            IdAvatar = 7,
                            NivelNecesar = 15,
                            NumeAvatar = "Mihai Viteazul",
                            UrlPoza = "Poze/Mihai_Viteazu.png"
                        });
                });

            modelBuilder.Entity("HistoryConnect.Models.CabinetInsigne", b =>
                {
                    b.Property<int>("IdUtilizator")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilizator");

                    b.Property<int>("IdInsigna")
                        .HasColumnType("integer")
                        .HasColumnName("id_insigna");

                    b.Property<DateTime>("DataObtinere")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_obtinere");

                    b.HasKey("IdUtilizator", "IdInsigna");

                    b.HasIndex("IdInsigna");

                    b.ToTable("cabinet_insigne", (string)null);
                });

            modelBuilder.Entity("HistoryConnect.Models.Capitol", b =>
                {
                    b.Property<int>("IdCapitol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_capitol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCapitol"));

                    b.Property<int>("IdPerioada")
                        .HasColumnType("integer")
                        .HasColumnName("id_perioada");

                    b.Property<int>("NrOrdine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("nr_ordine");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("titlu");

                    b.HasKey("IdCapitol");

                    b.HasIndex("IdPerioada");

                    b.HasIndex("Titlu")
                        .IsUnique();

                    b.ToTable("capitol", null, t =>
                        {
                            t.HasCheckConstraint("CK_capitol_nr_ordine_min_1", "nr_ordine >= 1");
                        });
                });

            modelBuilder.Entity("HistoryConnect.Models.Insigna", b =>
                {
                    b.Property<int>("IdInsigna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_insigna");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInsigna"));

                    b.Property<string>("ConditiiObtinere")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("conditii_obtinere");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nume");

                    b.Property<int>("PragConditie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("prag_conditie");

                    b.Property<string>("TipConditie")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tip_conditie");

                    b.Property<string>("UrlImagine")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("url_imagine");

                    b.HasKey("IdInsigna");

                    b.HasIndex("Nume")
                        .IsUnique();

                    b.ToTable("insigna", null, t =>
                        {
                            t.HasCheckConstraint("CK_insigna_prag_conditie_non_negative", "prag_conditie >= 0");

                            t.HasCheckConstraint("CK_insigna_tip_conditie_valid", "tip_conditie IN ('LectiiCompletate', 'QuizuriCompletate', 'ToateLectiile', 'XpAtins', 'NivelAtins')");
                        });
                });

            modelBuilder.Entity("HistoryConnect.Models.Intrebare", b =>
                {
                    b.Property<int>("IdIntrebare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_intrebare");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIntrebare"));

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("feedback");

                    b.Property<int>("IdQuiz")
                        .HasColumnType("integer")
                        .HasColumnName("id_quiz");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.Property<int>("Timp")
                        .HasColumnType("integer")
                        .HasColumnName("timp");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tip");

                    b.Property<string>("UrlImagine")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("url_imagine");

                    b.HasKey("IdIntrebare");

                    b.HasIndex("IdQuiz", "Text")
                        .IsUnique();

                    b.ToTable("intrebare", null, t =>
                        {
                            t.HasCheckConstraint("CK_intrebare_timp_min_5", "timp >= 5");

                            t.HasCheckConstraint("CK_intrebare_tip_valid", "tip IN ('Grila', 'AdevaratFals')");
                        });
                });

            modelBuilder.Entity("HistoryConnect.Models.IstoricRaspunsuri", b =>
                {
                    b.Property<int>("IdIstoric")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_istoric");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIstoric"));

                    b.Property<int>("IdIntrebare")
                        .HasColumnType("integer")
                        .HasColumnName("id_intrebare");

                    b.Property<int>("IdProgresQ")
                        .HasColumnType("integer")
                        .HasColumnName("id_progres_q");

                    b.Property<int>("IdUtilizator")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilizator");

                    b.Property<int?>("IdVarianta")
                        .HasColumnType("integer")
                        .HasColumnName("id_varianta");

                    b.HasKey("IdIstoric");

                    b.HasIndex("IdProgresQ");

                    b.HasIndex("IdUtilizator");

                    b.HasIndex("IdVarianta");

                    b.HasIndex("IdIntrebare", "IdProgresQ", "IdVarianta")
                        .IsUnique();

                    b.ToTable("istoric_raspunsuri", (string)null);
                });

            modelBuilder.Entity("HistoryConnect.Models.Lectie", b =>
                {
                    b.Property<int>("IdLectie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_lectie");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLectie"));

                    b.Property<int?>("AnEveniment")
                        .HasColumnType("integer")
                        .HasColumnName("an_eveniment");

                    b.Property<string>("Continut")
                        .HasColumnType("text")
                        .HasColumnName("continut");

                    b.Property<int>("IdCapitol")
                        .HasColumnType("integer")
                        .HasColumnName("id_capitol");

                    b.Property<int>("Ordine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("ordine");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tip");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titlu");

                    b.Property<string>("UrlImagine")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("url_imagine");

                    b.HasKey("IdLectie");

                    b.HasIndex("IdCapitol");

                    b.HasIndex("Titlu")
                        .IsUnique();

                    b.ToTable("lectie", null, t =>
                        {
                            t.HasCheckConstraint("CK_lectie_ordine_min_1", "ordine >= 1");

                            t.HasCheckConstraint("CK_lectie_tip_valid", "tip IN ('Istorie', 'Traditii')");
                        });
                });

            modelBuilder.Entity("HistoryConnect.Models.Perioada", b =>
                {
                    b.Property<int>("IdPerioada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_perioada");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPerioada"));

                    b.Property<string>("Descriere")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descriere");

                    b.Property<int?>("Inceput")
                        .HasColumnType("integer")
                        .HasColumnName("inceput");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nume");

                    b.Property<int?>("Sfarsit")
                        .HasColumnType("integer")
                        .HasColumnName("sfarsit");

                    b.Property<string>("UrlImagine")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("url_imagine");

                    b.HasKey("IdPerioada");

                    b.HasIndex("Nume")
                        .IsUnique();

                    b.ToTable("perioada", null, t =>
                        {
                            t.HasCheckConstraint("CK_perioada_interval_valid", "inceput IS NULL OR sfarsit IS NULL OR sfarsit > inceput");
                        });
                });

            modelBuilder.Entity("HistoryConnect.Models.ProgresLectie", b =>
                {
                    b.Property<int>("IdProgresL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_progres_l");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProgresL"));

                    b.Property<bool>("Completata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("completata");

                    b.Property<DateTime?>("DataCompletare")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_completare");

                    b.Property<int>("IdLectie")
                        .HasColumnType("integer")
                        .HasColumnName("id_lectie");

                    b.Property<int>("IdUtilizator")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilizator");

                    b.HasKey("IdProgresL");

                    b.HasIndex("IdLectie");

                    b.HasIndex("IdUtilizator", "IdLectie")
                        .IsUnique();

                    b.ToTable("progres_lectie", (string)null);
                });

            modelBuilder.Entity("HistoryConnect.Models.ProgresQuiz", b =>
                {
                    b.Property<int>("IdProgresQ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_progres_q");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProgresQ"));

                    b.Property<DateTime>("DataCompletare")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_completare");

                    b.Property<bool>("Evaluat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("evaluat");

                    b.Property<int>("IdQuiz")
                        .HasColumnType("integer")
                        .HasColumnName("id_quiz");

                    b.Property<int>("IdUtilizator")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilizator");

                    b.Property<int>("Scor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("scor");

                    b.Property<int>("XpAcordat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("xp_acordat");

                    b.HasKey("IdProgresQ");

                    b.HasIndex("IdQuiz");

                    b.HasIndex("IdUtilizator", "IdQuiz", "DataCompletare")
                        .IsUnique();

                    b.ToTable("progres_quiz", null, t =>
                        {
                            t.HasCheckConstraint("CK_progres_quiz_scor_valid", "scor >= 0 AND scor <= 100");

                            t.HasCheckConstraint("CK_progres_quiz_xp_acordat_non_negative", "xp_acordat >= 0");
                        });
                });

            modelBuilder.Entity("HistoryConnect.Models.Quiz", b =>
                {
                    b.Property<int>("IdQuiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_quiz");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdQuiz"));

                    b.Property<string>("Feedback")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("feedback");

                    b.Property<int>("IdLectie")
                        .HasColumnType("integer")
                        .HasColumnName("id_lectie");

                    b.Property<int>("Timp")
                        .HasColumnType("integer")
                        .HasColumnName("timp");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titlu");

                    b.Property<int>("XpCompletare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("xp_completare");

                    b.HasKey("IdQuiz");

                    b.HasIndex("IdLectie", "Titlu")
                        .IsUnique();

                    b.ToTable("quiz", null, t =>
                        {
                            t.HasCheckConstraint("CK_quiz_timp_positive", "timp > 0");

                            t.HasCheckConstraint("CK_quiz_xp_completare_non_negative", "xp_completare >= 0");
                        });
                });

            modelBuilder.Entity("HistoryConnect.Models.Student", b =>
                {
                    b.Property<int>("IdUtilizator")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilizator");

                    b.Property<int>("NivelCurent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("nivel_curent");

                    b.Property<int>("XpTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("xp_total");

                    b.HasKey("IdUtilizator");

                    b.ToTable("student", null, t =>
                        {
                            t.HasCheckConstraint("CK_student_nivel_curent_min_1", "nivel_curent >= 1");

                            t.HasCheckConstraint("CK_student_xp_total_non_negative", "xp_total >= 0");
                        });
                });

            modelBuilder.Entity("HistoryConnect.Models.Utilizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_utilizator");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataInregistrare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inregistrare")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("IdAvatar")
                        .HasColumnType("integer")
                        .HasColumnName("id_avatar");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nume");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parola");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdAvatar");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("utilizator", (string)null);
                });

            modelBuilder.Entity("HistoryConnect.Models.VariantaRaspuns", b =>
                {
                    b.Property<int>("IdVarianta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_varianta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVarianta"));

                    b.Property<bool>("Corect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("corect");

                    b.Property<int>("IdIntrebare")
                        .HasColumnType("integer")
                        .HasColumnName("id_intrebare");

                    b.Property<int>("Punctaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("punctaj");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("text");

                    b.HasKey("IdVarianta");

                    b.HasIndex("IdIntrebare", "Text")
                        .IsUnique();

                    b.ToTable("varianta_raspuns", null, t =>
                        {
                            t.HasCheckConstraint("CK_varianta_raspuns_punctaj_non_negative", "punctaj >= 0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roluri", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("rol_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("utilizator_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("utilizator_loginuri", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("utilizator_roluri", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("utilizator_tokeni", (string)null);
                });

            modelBuilder.Entity("HistoryConnect.Models.Administrator", b =>
                {
                    b.HasOne("HistoryConnect.Models.Utilizator", "Utilizator")
                        .WithOne("Administrator")
                        .HasForeignKey("HistoryConnect.Models.Administrator", "IdUtilizator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("HistoryConnect.Models.CabinetInsigne", b =>
                {
                    b.HasOne("HistoryConnect.Models.Insigna", "Insigna")
                        .WithMany()
                        .HasForeignKey("IdInsigna")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HistoryConnect.Models.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("IdUtilizator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insigna");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("HistoryConnect.Models.Capitol", b =>
                {
                    b.HasOne("HistoryConnect.Models.Perioada", "Perioada")
                        .WithMany("Capitole")
                        .HasForeignKey("IdPerioada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perioada");
                });

            modelBuilder.Entity("HistoryConnect.Models.Intrebare", b =>
                {
                    b.HasOne("HistoryConnect.Models.Quiz", "Quiz")
                        .WithMany("Intrebari")
                        .HasForeignKey("IdQuiz")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("HistoryConnect.Models.IstoricRaspunsuri", b =>
                {
                    b.HasOne("HistoryConnect.Models.Intrebare", "Intrebare")
                        .WithMany()
                        .HasForeignKey("IdIntrebare")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HistoryConnect.Models.ProgresQuiz", "ProgresQuiz")
                        .WithMany()
                        .HasForeignKey("IdProgresQ")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HistoryConnect.Models.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("IdUtilizator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HistoryConnect.Models.VariantaRaspuns", "VariantaRaspuns")
                        .WithMany()
                        .HasForeignKey("IdVarianta")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Intrebare");

                    b.Navigation("ProgresQuiz");

                    b.Navigation("Utilizator");

                    b.Navigation("VariantaRaspuns");
                });

            modelBuilder.Entity("HistoryConnect.Models.Lectie", b =>
                {
                    b.HasOne("HistoryConnect.Models.Capitol", "Capitol")
                        .WithMany("Lectii")
                        .HasForeignKey("IdCapitol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capitol");
                });

            modelBuilder.Entity("HistoryConnect.Models.ProgresLectie", b =>
                {
                    b.HasOne("HistoryConnect.Models.Lectie", "Lectie")
                        .WithMany()
                        .HasForeignKey("IdLectie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HistoryConnect.Models.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("IdUtilizator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lectie");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("HistoryConnect.Models.ProgresQuiz", b =>
                {
                    b.HasOne("HistoryConnect.Models.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("IdQuiz")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HistoryConnect.Models.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("IdUtilizator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("HistoryConnect.Models.Quiz", b =>
                {
                    b.HasOne("HistoryConnect.Models.Lectie", "Lectie")
                        .WithMany("Quizuri")
                        .HasForeignKey("IdLectie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lectie");
                });

            modelBuilder.Entity("HistoryConnect.Models.Student", b =>
                {
                    b.HasOne("HistoryConnect.Models.Utilizator", "Utilizator")
                        .WithOne("Student")
                        .HasForeignKey("HistoryConnect.Models.Student", "IdUtilizator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("HistoryConnect.Models.Utilizator", b =>
                {
                    b.HasOne("HistoryConnect.Models.Avatar", "Avatar")
                        .WithMany()
                        .HasForeignKey("IdAvatar")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("HistoryConnect.Models.VariantaRaspuns", b =>
                {
                    b.HasOne("HistoryConnect.Models.Intrebare", "Intrebare")
                        .WithMany("Variante")
                        .HasForeignKey("IdIntrebare")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intrebare");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("HistoryConnect.Models.Utilizator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("HistoryConnect.Models.Utilizator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HistoryConnect.Models.Utilizator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("HistoryConnect.Models.Utilizator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HistoryConnect.Models.Capitol", b =>
                {
                    b.Navigation("Lectii");
                });

            modelBuilder.Entity("HistoryConnect.Models.Intrebare", b =>
                {
                    b.Navigation("Variante");
                });

            modelBuilder.Entity("HistoryConnect.Models.Lectie", b =>
                {
                    b.Navigation("Quizuri");
                });

            modelBuilder.Entity("HistoryConnect.Models.Perioada", b =>
                {
                    b.Navigation("Capitole");
                });

            modelBuilder.Entity("HistoryConnect.Models.Quiz", b =>
                {
                    b.Navigation("Intrebari");
                });

            modelBuilder.Entity("HistoryConnect.Models.Utilizator", b =>
                {
                    b.Navigation("Administrator");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
